### ISSUE TITLE
Dead domains during tests

### ISSUE THREAD

**Issue by kowith337** [kowith337/ThaiParanoidBlock#10]
Checklist of dead domains
- [x] `aroundnews.net`: Dead, but it seems site still alive, but have no contents.
  > Apache is functioning normally
- [x] `chujai.com`: Dead, redirect to `/?z`
- [x] `clip-th.com`: Officially suspended.
  > This account has been suspended.
  > Either the domain has been overused, or the reseller ran out of resources.
- [x] `coregamerth.com`: https://github.com/kowith337/ThaiParanoidBlock/issues/10#issuecomment-440364944
- [x] `doodiza.com`: Seems to be dead. (redirect to resale)
- [x] `ithaihotnews.com`: Confirmed dead, name not resolved.
- [x] `juropy.com`: https://github.com/kowith337/ThaiParanoidBlock/issues/10#issuecomment-440364944
- [x] `(hot.)kodlikes.com`: Seems to be dead, awaiting for sale.
- [x] `ladycee.com`: Confirmed this domain is dead, name not resolved.
- [x] `laughwoo.com`: Confirmed this domain is dead, name not resolved.
- [x] `liceza.com`: Confirmed this domain is dead, name not resolved.
- [x] `manyum.com`: https://github.com/kowith337/ThaiParanoidBlock/issues/10#issuecomment-440364944
- [ ] #18
- [x] `picnic.ly`: parked by `park.io`
- [x] `siamchatroom.com`: Seems to be dead, by scam redirect.
- [x] `sudting.party`: Confirmed this domain is dead, name not resolved.
- [x] `toritalk.com`: Redirect to HugeDomains. (It's mean this domain is for sale)
- [x] `yakjado.com`: Confirmed this domain is dead, name not resolved.
- [x] `yaklai.com`: Page code is empty

**Comment by bogachenko** [comment]
dead
1. coregamerth.com
2. juropy.com
3. manyum.com

live
1. oopsmobile.net
2. picnic.ly

blank page, page source is empty
1. yaklai.com
