### ISSUE TITLE
Youtube doesn't keep history

### ISSUE THREAD

**Issue by maxjame5432** [kowith337/ThaiParanoidBlock#8]
## เว็บไซท์ (Websites)
youtueb.com

## ประเภทของการแจ้ง (Report type)
ตัว Youtube ไม่ยอมเก็บประวัติการเข้าชมย้อนหลังไว้เมื่อเปิดใช้ตัวบล็อกของคุณ

## ขั้นตอนการทำซ้ำ (Steps to reproduce)
ลองเปิด-ปิดตัวลิสต์ซ้ำไปซ้ำมาของคุณ แล้วก็ยกเว้นตัว
`s.youtube.com/api/stats/playback?$object-subrequest`
ก็ยังไม่เป็นผล

## บราวเซอร์และส่วนเสริมที่ใช้อยู่ (Your browser and add-ons)
- Browser: Chrome 68.0.3440.106
- uBlock0 Version: 1.16.16

**Comment by kowith337** [comment]
มันติดบล็อคตรงที่
- `||s.youtube.com$important` กับ
- `||youtube.com/api/stats$important` ครับ 

แล้วการใส่ `$important` ไว้ หมายความว่า uBlock จะไม่สนใจ Whitelist ใดๆ ที่เกี่ยวข้องกับ Address ที่บล็อคไว้แล้ว
อันนี้โดยส่วนตัว ปกติผมปิด History ทุกอย่างทั้งใน Google และ YouTube (อันนี้ Concern ส่วนตัว) ถ้ายังไงเดี๋ยวผมใส่ Whitelist ใน Commit ครั้งต่อไปให้ ส่วนใน Branch Maximum ผมจะคงไว้

**Comment by kowith337** [comment]
Probably solved, no feedback.
